name: Validate
on:
  push:
    branches:
      - "**"
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      # Cache the virtual environment
      - name: Cache virtual environment
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: |
            .venv
            ~/.cache/pip
          key: venv-${{ runner.os }}-py3.12-${{ hashFiles('**/pyproject.toml', '**/setup.cfg', '**/requirements*.txt') }}
          restore-keys: |
            venv-${{ runner.os }}-py3.12-

      - name: Install dependencies
        run: |
          if [ ! -d ".venv" ]; then
            python -m venv .venv
          fi
          source .venv/bin/activate
          python -m pip install --upgrade pip
          if [ "${{ steps.cache-venv.outputs.cache-hit }}" != "true" ]; then
            pip install .[dev]
          fi

      - name: Run validation
        id: validate
        run: |
          source .venv/bin/activate
          ruff check . --ignore=C901
          pytest tests/ -v --cov=cloud_inspector --cov-report=xml --cov-report=term

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
